-- Keymaps are automatically loaded on the VeryLazy event
-- Default keymaps that are always set: https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/config/keymaps.lua
-- Add any additional keymaps here
--
-- vim.keymap.set("n", ";", ":", { desc = "CMD enter command mode" })
-- https://github.com/neovim/neovim/issues/11804#issuecomment-1113927971
-- vim.keymap.set("n", "x", '"_x')
